name: Deploy
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3  #use an action from github marketplace from actions
            - name: Install NodeJs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Run Lint
              run: npm lint
            - name: Run Test
              run: npm test
            - name: Deploy
              run: echo "Deploying . . . "    